import type { Nuxt } from '@nuxt/schema'
import type { RsbuildPlugin, Rspack } from '@rsbuild/core'

/**
 * Expose the Rsbuild lifecycle through Nuxt hooks.
 */
export function NuxtHooksPlugin (nuxt: Nuxt): RsbuildPlugin {
  return {
    name: 'nuxt:hooks',
    setup (api) {
      // The Rspack configurations generated by Rsbuild are passed to the `rspack:*` hooks, so that
      // plugins registered with `addRspackPlugin` (or `addBuildPlugin` without an `rsbuild` variant)
      // are still applied when there is no Rsbuild-native equivalent.
      api.onBeforeCreateCompiler(async ({ bundlerConfigs }) => {
        // the `rspack:*` hooks are typed with webpack's configuration
        await nuxt.callHook('rspack:config', bundlerConfigs as any)

        // ensure the Vue loader plugin is applied first, before other plugins add rules matching `.vue` files
        for (const config of bundlerConfigs) {
          const index = config.plugins?.findIndex(plugin => plugin?.constructor?.name === 'VueLoaderPlugin') ?? -1
          if (index > 0) {
            config.plugins!.unshift(...config.plugins!.splice(index, 1))
          }
        }

        await nuxt.callHook('rspack:configResolved', bundlerConfigs as any)
      })

      let compilers: Rspack.Compiler[] = []
      api.onAfterCreateCompiler(({ compiler }) => {
        compilers = 'compilers' in compiler ? compiler.compilers : [compiler]
      })

      // in development, the dev server replaces the output file system of the compilers before the first compilation
      api.onBeforeEnvironmentCompile(async ({ environment, isFirstCompile }) => {
        const compiler = compilers.find(compiler => compiler.options.name === environment.name)
        if (isFirstCompile && compiler) {
          await nuxt.callHook('rsbuild:compile', { name: environment.name, compiler })
        }
      })

      api.onAfterEnvironmentCompile(async ({ environment, stats }) => {
        if (stats) {
          await nuxt.callHook('rsbuild:compiled', { name: environment.name, compiler: stats.compilation.compiler, stats })
        }
      })
    },
  }
}
