import type { Nuxt } from '@nuxt/schema'
import type { RsbuildPlugin, Rspack } from '@rsbuild/core'
import { directoryToURL, resolveAlias } from '@nuxt/kit'
import { resolveModulePath } from 'exsolve'
import { genObjectFromRawEntries, genString } from 'knitwork'
import { parseNodeModulePath } from 'mlly'
import { isAbsolute, normalize, resolve } from 'pathe'

import { stripInvalidPureAnnotations } from '../../../webpack/src/plugins/strip-invalid-pure-annotations.ts'

const JS_RE = /\.[cm]?js(?:\?[^.]+)?$/
const ASSET_RE = /\.(?:css|s[ca]ss|png|jpe?g|gif|svg|woff2?|eot|ttf|otf|webp|webm|mp4|ogv)(?:\?.*)?$/i
const VIRTUAL_RE = /^\0?virtual:(?:nuxt:)?/

const DYNAMIC_IMPORT_RE = /import\([^)]*\+\s*__webpack_require__[^+]*\)\.then/
const DYNAMIC_IMPORT_REPLACE_RE = /import\([^)]*\+\s*(__webpack_require__[^+]*)\)\.then/g
const HELPER_FILENAME = '_dynamic-import-helper.mjs'
const HELPER_IMPORT = `import { _rollupDynamicImport } from "./${HELPER_FILENAME}";\n`

type ExternalItemFunction = Extract<Rspack.ExternalItem, (...args: any[]) => unknown>

/**
 * Adapt the server build to be bundled by Nitro.
 */
export function ServerPlugin (nuxt: Nuxt): RsbuildPlugin {
  return {
    name: 'nuxt:server',
    setup (api) {
      if (nuxt.options.dev) {
        api.modifyRspackConfig((config, { environment }) => {
          if (environment.name !== 'server') { return }
          // Nitro loads the server bundle from memory as a single file in development
          config.output ||= {}
          config.output.asyncChunks = false
        })
        return
      }

      api.processAssets({ stage: 'optimize-inline', environments: ['server'] }, ({ assets, compilation, sources }) => {
        const entryFiles = new Set<string>()
        for (const chunk of compilation.chunks) {
          // entry and runtime chunks contain the code loading other chunks
          if (chunk.canBeInitial() || chunk.hasRuntime()) {
            for (const file of chunk.files) {
              entryFiles.add(file)
            }
          }
        }

        const chunkFiles: string[] = []
        for (const chunk of compilation.chunks) {
          if (chunk.hasRuntime()) { continue }
          for (const file of chunk.files) {
            if (JS_RE.test(file)) {
              chunkFiles.push(file)
            }
          }
        }

        for (const filename in assets) {
          if (!JS_RE.test(filename)) { continue }

          const code = assets[filename]!.source().toString()
          let transformed = stripInvalidPureAnnotations(code)

          // emit explicit dynamic import statements, so the chunks can be analysed when Nitro bundles the server
          if (entryFiles.has(filename) && DYNAMIC_IMPORT_RE.test(transformed)) {
            transformed = HELPER_IMPORT + transformed.replace(DYNAMIC_IMPORT_REPLACE_RE, (_, chunkId) => `_rollupDynamicImport(${chunkId}).then`)
          }

          if (transformed !== code) {
            compilation.updateAsset(filename, new sources.RawSource(transformed))
          }
        }

        if (chunkFiles.length) {
          compilation.emitAsset(HELPER_FILENAME, new sources.RawSource(generateDynamicImportHelper(chunkFiles)))
        }
      })
    },
  }
}

function generateDynamicImportHelper (chunkFiles: string[]) {
  return `
// Rollup-compatible dynamic import helper generated by Rsbuild
const chunkMap = ${genObjectFromRawEntries(chunkFiles.map(filename => [filename, `() => import(${genString('./' + filename)})`]))}

export function _rollupDynamicImport(chunkId) {
  const chunk = chunkMap[chunkId]
  if (!chunk) {
    return Promise.reject(new Error(\`Chunk \${chunkId} not found in chunkMap. Available chunks: \${Object.keys(chunkMap).join(', ')}\`))
  }
  return chunk()
}
`
}

/**
 * Bundle the Nuxt app and its dependencies that need to be transpiled, and leave other dependencies
 * to be resolved (and traced) by Nitro.
 */
export function createServerExternals (nuxt: Nuxt): ExternalItemFunction {
  const inline = [
    'src/',
    '#app',
    'nuxt',
    'nuxt3',
    'nuxt-nightly',
    '!',
    '-!',
    '~',
    '@/',
    '#',
    // SWC helpers are resolved from Rsbuild's own dependencies
    '@swc/helpers',
    ...nuxt.options.build.transpile.filter((pattern): pattern is string => typeof pattern === 'string'),
  ]

  const external = new Set([
    'nitro/runtime-config',
    // TODO: remove in v5
    '#internal/nitro',
    'nitropack/runtime',
    '#shared',
    resolve(nuxt.options.rootDir, nuxt.options.dir.shared),
    ...nuxt['~runtimeDependencies'] || [],
  ])
  if (!nuxt.options.dev) {
    external.add('#internal/nuxt/paths')
    external.add('#internal/nuxt/app-config')
    external.add('#app-manifest')
  }

  // Resolve conditions for server build
  const conditions = [
    nuxt.options.dev ? 'development' : 'production',
    'node',
    'import',
    'require',
  ]

  return ({ request, context }, callback) => {
    if (!request) {
      return callback(undefined, false)
    }
    if (external.has(request)) {
      // Resolve to absolute path so nitro can handle version resolution
      const resolved = resolveModulePath(request, {
        from: (context ? [context, ...nuxt.options.modulesDir] : nuxt.options.modulesDir).map(d => directoryToURL(d)),
        suffixes: ['', 'index'],
        conditions,
        try: true,
      })
      return callback(undefined, resolved && isAbsolute(resolved) ? resolved : true)
    }
    if (
      request[0] === '.' ||
      isAbsolute(request) ||
      inline.some(prefix => request.startsWith(prefix)) ||
      ASSET_RE.test(request)
    ) {
      return callback(undefined, false)
    }

    if (context && !request.startsWith('node:') && (isAbsolute(context) || VIRTUAL_RE.test(context))) {
      try {
        const normalisedRequest = resolveAlias(normalize(request), nuxt.options.alias)
        const dir = parseNodeModulePath(context).dir || nuxt.options.rootDir

        const resolved = resolveModulePath(normalisedRequest, {
          from: [dir, ...nuxt.options.modulesDir].map(d => directoryToURL(d)),
          suffixes: ['', 'index'],
          conditions,
          try: true,
        })

        if (resolved && isAbsolute(resolved)) {
          return callback(undefined, false)
        }
      } catch {
        // Ignore resolution errors, fall through to externalize
      }
    }

    return callback(undefined, true)
  }
}
