import { createHash } from 'node:crypto'

import type { Nuxt } from '@nuxt/schema'
import type { RsbuildPlugin, Rspack } from '@rsbuild/core'
import { resolveAlias } from '@nuxt/kit'
import { normalize } from 'pathe'

import { SSRStylesPlugin as SSRStylesRspackPlugin } from '../../../webpack/src/plugins/ssr-styles.ts'

/**
 * Inline the styles of components rendered on the server.
 */
export function SSRStylesPlugin (nuxt: Nuxt): RsbuildPlugin {
  return {
    name: 'nuxt:ssr-styles',
    setup (api) {
      const inlineStyles = nuxt.options.features.inlineStyles
      if (inlineStyles) {
        const globalCSSPaths = new Set<string>()
        for (const css of nuxt.options.css) {
          if (typeof css === 'string') {
            globalCSSPaths.add(normalize(resolveAlias(css, nuxt.options.alias)))
          }
        }

        // separate global CSS into a dedicated chunk
        if (globalCSSPaths.size) {
          api.modifyBundlerChain((chain, { environment }) => {
            if (environment.name !== 'client') { return }
            const splitChunks = chain.optimization.splitChunks.values() as Rspack.OptimizationSplitChunksOptions | false
            if (!splitChunks) { return }
            chain.optimization.splitChunks({
              ...splitChunks,
              cacheGroups: {
                ...splitChunks.cacheGroups,
                nuxtGlobalCSS: {
                  name: 'nuxt-global-css',
                  chunks: 'all',
                  enforce: true,
                  test: (module: Rspack.Module) => {
                    if (module.type !== 'css/mini-extract') { return false }
                    const identifier = normalize(module.identifier())
                    for (const globalPath of globalCSSPaths) {
                      if (identifier.includes(globalPath)) {
                        return typeof inlineStyles === 'boolean' ? inlineStyles : inlineStyles(module.identifier())
                      }
                    }
                    return false
                  },
                },
              },
            })
          })
        }
      }

      if (!nuxt.options.ssr || nuxt.options.dev) { return }

      // Rsbuild has no equivalent: the Rspack plugin shared with the webpack builder collects
      // the CSS emitted by the client build and emits it as modules of the server build.
      const ssrStylesPlugin = new SSRStylesRspackPlugin(nuxt, {
        // scope IDs generated by `rspack-vue-loader`
        getVueLoaderHash: value => createHash('sha256').update(value).digest('hex').substring(0, 8),
      })
      api.modifyRspackConfig((config, { environment }) => {
        config.plugins ||= []
        config.plugins.push(ssrStylesPlugin as unknown as Rspack.RspackPluginInstance)
        if (environment.name === 'server') {
          // the server build needs the styles collected from the client build
          config.dependencies = ['client']
        }
      })
    },
  }
}
