export const start = () => import('./start')
export const dev = () => import('./dev')
export const ui = () => import('./ui')
export const build = () => import('./build')
export const generate = () => import('./generate')
