# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: nuxtjs
tidelift: npm/nuxt
custom: https://otechie.com/nuxt
