packages:
  - docs
  - packages/**
  - '!packages/nuxi'
  - '!packages/test-utils'
  - '!packages/nuxt/test/package-fixture/pkg'
  - playground
  - test/fixtures/*
  - test/fixtures/*/_local-modules/*

patchedDependencies:
  changelogen: patches/changelogen.patch

publicHoistPattern:
  - '*-loader'
  - 'webpack-*'

shellEmulator: true

verifyDepsBeforeRun: install

ignoreWorkspaceCycles: true

overrides:
  "@nuxt/kit": "workspace:*"
  "@nuxt/schema": "workspace:*"
  nuxt: "workspace:*"
  oxc-parser: "0.140.0"
  vite: "8.1.5"
  vue: "3.5.40"

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: false

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@nuxt/*'
  - fnv1a-64
  # Renovate security update: esbuild@0.28.1
  - esbuild@0.28.1
  - vue-bundle-renderer
  # Renovate security update: undici@8.5.0
  - undici@8.5.0
  - unctx@3.0.0-beta.2
  - magic-string@1.0.0
  - verkit@0.1.2
