packages:
  - packages/**
  - playground
  - test/fixtures/*
catalog:
  "@eslint/js": 9.6.0
  "@nuxt/devalue": ^2.0.2
  "@nuxt/devtools": ^1.3.9
  "@nuxt/eslint-config": 0.3.13
  "@nuxt/friendly-errors-webpack-plugin": ^2.6.0
  "@nuxt/scripts": 0.6.3
  "@nuxt/test-utils": 3.13.1
  "@nuxt/ui-templates": 1.3.4
  "@parcel/watcher": 2.4.1
  "@rollup/plugin-replace": ^5.0.7
  "@testing-library/vue": 8.1.0
  "@types/clear": 0.1.4
  "@types/eslint__js": 8.42.3
  "@types/estree": 1.0.5
  "@types/file-loader": 5.0.4
  "@types/hash-sum": 1.0.2
  "@types/html-minifier": 4.0.5
  "@types/lodash-es": 4.17.12
  "@types/node": 20.14.10
  "@types/pify": 5.0.4
  "@types/pug": 2.0.10
  "@types/sass-loader": 8.0.8
  "@types/semver": 7.5.8
  "@types/webpack-bundle-analyzer": 4.7.0
  "@types/webpack-hot-middleware": 2.25.9
  "@unhead/dom": ^1.9.15
  "@unhead/schema": 1.9.15
  "@unhead/ssr": ^1.9.15
  "@unhead/vue": ^1.9.15
  "@unocss/reset": 0.61.3
  "@vitest/coverage-v8": 1.6.0
  "@vue/compiler-core": 3.4.31
  "@vue/compiler-sfc": 3.4.31
  "@vue/language-core": 2.0.26
  "@vue/shared": ^3.4.31
  "@vue/test-utils": 2.4.6
  acorn: 8.12.1
  case-police: 0.6.1
  changelogen: 0.5.5
  chokidar: ^3.6.0
  clear: ^0.1.0
  compatx: ^0.1.8
  cookie-es: ^1.1.0
  critters: 0.0.24
  css-loader: ^7.1.2
  css-minimizer-webpack-plugin: ^7.0.0
  defu: ^6.1.4
  destr: ^2.0.3
  esbuild: ^0.23.0
  escape-string-regexp: ^5.0.0
  eslint: 9.6.0
  eslint-plugin-no-only-tests: 3.1.0
  eslint-plugin-perfectionist: 2.11.0
  eslint-typegen: 0.2.4
  estree-walker: ^3.0.3
  execa: 9.3.0
  externality: ^1.0.2
  file-loader: ^6.2.0
  fork-ts-checker-webpack-plugin: ^9.0.2
  get-port-please: ^3.1.2
  h3: npm:h3-nightly@2.0.0-1718872656.6765a6e
  happy-dom: 14.12.3
  hash-sum: ^2.0.0
  hookable: ^5.5.3
  html-minifier: 4.0.0
  html-validate: 8.20.1
  klona: ^2.0.6
  lodash-es: 4.17.21
  magic-string: ^0.30.10
  markdownlint-cli: 0.41.0
  memfs: ^4.9.3
  mini-css-extract-plugin: ^2.9.0
  mlly: ^1.7.1
  nitro: npm:nitro-nightly@3.0.0-beta-28665895.e727afda
  nuxt-content-twoslash: 0.1.0
  nypm: ^0.3.9
  ohash: ^1.1.3
  perfect-debounce: ^1.0.0
  pify: ^6.1.0
  pkg-types: ^1.1.3
  playwright-core: 1.45.1
  postcss: ^8.4.39
  postcss-import: ^16.1.0
  postcss-import-resolver: ^2.0.0
  postcss-loader: ^8.1.1
  postcss-url: ^10.1.3
  prettier: 3.3.2
  pug-plain-loader: ^1.1.0
  radix3: ^1.1.2
  rimraf: 6.0.1
  rollup: 4.18.1
  rollup-plugin-visualizer: ^5.12.0
  strip-literal: ^2.1.0
  time-fix-plugin: ^2.0.7
  typescript: 5.5.3
  ultrahtml: ^1.5.3
  unbuild: 3.0.0-rc.6
  uncrypto: ^0.1.3
  unimport: ^3.7.2
  unocss: 0.61.3
  unplugin: ^1.11.0
  unplugin-vue-router: ^0.10.0
  unstorage: ^1.10.2
  untyped: ^1.4.2
  url-loader: ^4.1.1
  vite-node: ^1.6.0
  vite-plugin-checker: 0.7.0
  vitest: 1.6.0
  vitest-environment-nuxt: 1.0.0
  vue-devtools-stub: ^0.1.0
  vue-tsc: 2.0.26
  webpack-bundle-analyzer: ^4.10.2
  webpack-hot-middleware: ^2.26.1
  webpack-virtual-modules: ^0.6.2
  webpackbar: ^6.0.1
