packages:
  - docs
  - packages/**
  - '!packages/nuxi'
  - '!packages/test-utils'
  - playground
  - test/fixtures/*

ignoredBuiltDependencies:
  - esbuild
  - oxc-resolver
  - unrs-resolver
  - vue-demi
