packages:
  - docs
  - packages/**
  - '!packages/nuxi'
  - '!packages/test-utils'
  - '!packages/nuxt/test/package-fixture/pkg'
  - playground
  - test/fixtures/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - oxc-resolver
  - unrs-resolver

overrides:
  '@nuxt/kit': workspace:*
  '@nuxt/nitro-server': workspace:*
  '@nuxt/rspack-builder': workspace:*
  '@nuxt/schema': workspace:*
  '@nuxt/vite-builder': workspace:*
  '@nuxt/webpack-builder': workspace:*
  '@vue/compiler-core': 3.5.33
  '@vue/compiler-dom': 3.5.33
  '@vue/shared': 3.5.33
  nuxt: workspace:*
  send: '>=1.2.1'
  vite: '^7.3.2'
  vue: 3.5.33
  typescript: 5.9.3

patchedDependencies:
  changelogen: patches/changelogen.patch

publicHoistPattern:
  - '*-loader'
  - 'webpack-*'

shellEmulator: true
