declare module '@nuxt/schema' {
  interface NuxtHooks {
    /**
     * Test hook installed by `_local-modules/hook-augmenting-module`. Augments
     * `@nuxt/schema { interface NuxtHooks }` and is pulled into the program via
     * `<reference types="hook-augmenting-module" />` generated by `nuxt prepare`.
     *
     * Used to verify that `declare module '@nuxt/schema'` augmentations entering
     * through a `<reference types>` boundary reach `NuxtConfig['hooks']` when
     * accessed via `nuxt/schema` (the path `defineNuxtConfig` types take).
     */
    'hook-augmenting-module:ping': (payload: { value: number }) => void
  }
}

export {}
