import { defineBuildConfig } from 'obuild/config'

export default defineBuildConfig({
  entries: [
    {
      type: 'bundle',
      input: ['src/index', 'src/builder-env'],
      dts: { oxc: true },
      rolldown: {
        external: [
          // Type imports
          '@unhead/vue/types',
          '@vitejs/plugin-vue',
          '@vitejs/plugin-vue-jsx',
          '@vue/compiler-core',
          '@vue/compiler-sfc',
          '@vue/language-core',
          'c12',
          'chokidar',
          'compatx',
          'css-minimizer-webpack-plugin',
          'esbuild',
          'esbuild-loader',
          'file-loader',
          'h3',
          'hookable',
          'ignore',
          'mini-css-extract-plugin',
          'nuxt/app',
          'ofetch',
          'oxc-transform',
          'postcss',
          'pug',
          'rollup-plugin-visualizer',
          'sass-loader',
          'scule',
          'unctx/transform',
          'unimport',
          'untyped',
          'vite',
          'vue',
          'vue-bundle-renderer',
          'vue-loader',
          'vue-router',
          'webpack',
          'webpack-bundle-analyzer',
          'webpack-dev-middleware',
          'webpack-hot-middleware',
          // Implicit
          'autoprefixer',
          'cssnano',
        ],
      },
    },
  ],
})
