name: "🚀 Feature request"
description: Suggest a feature that will improve Nuxt
labels: ["pending triage", "3.x"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request!

        Please carefully read the contribution docs before suggesting a new feature
        👉 https://nuxt.com/docs/community/contribution/#creating-an-issue
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you think would be a helpful addition to Nuxt, including the possible use cases and alternatives you have considered. If you have a working prototype or module that implements it, please include a link.
      placeholder: Feature description
    validations:
      required: true
  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional information
      description: Additional information that helps us decide how to proceed.
      options:
        - label: Would you be willing to help implement this feature?
        - label: Could this feature be implemented as a module?
  - type: checkboxes
    id: required-info
    attributes:
      label: Final checks
      description: Before submitting, please make sure you do the following
      options:
        - label: Read the [contribution guide](https://nuxt.com/docs/community/contribution).
          required: true
        - label: Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).
          required: true
