// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference types="nuxt3" />
/// <reference types="@nuxt/kit" />
/// <reference types="@nuxt/nitro" />
/// <reference path=".nuxt/components.d.ts" />
/// <reference path=".nuxt/auto-imports.d.ts" />
export {}
