// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference types="@nuxt/kit" />
/// <reference types="#app" />
/// <reference types="@nuxt/nitro" />
/// <reference path=".nuxt/components.d.ts" />
export {}
