// @ts-expect-error : we are importing from the virtual file system
import contentSecurityPolicyConfig from '#content-security-policy'
import type { NitroApp } from 'nitro/types'
import type { ContentSecurityPolicyConfig, ContentSecurityPolicyValue } from '../../../types'
import { headerStringFromObject } from '../../../utils'
import type { ServerRequestContext } from 'srvx'

/**
 * This plugin updates the CSP directives with the nonce and hashes generated by the server.
 */
export default (nitroApp: NitroApp) => {
  const cspConfig = contentSecurityPolicyConfig as ContentSecurityPolicyConfig

  nitroApp.hooks?.hook('render:html', (_, { event }) => {
    if (cspConfig && cspConfig.value) {
      const config = cspConfig

      const securityContext = event.req.context!.security as ServerRequestContext[string] & { hashes?: { script?: Set<string>, style?: Set<string> }, nonce: string }

      if (config.value) {
        const csp = config.value
        const nonce = securityContext.nonce
        const scriptHashes = securityContext.hashes?.script
        const styleHashes = securityContext.hashes?.style
        config.value = updateCspVariables(csp, nonce, scriptHashes, styleHashes)
      }

      const headerValue = headerStringFromObject(config.value)
      const headerName = cspConfig.reportOnly ? 'content-security-policy-report-only' : 'content-security-policy'
      event.res.headers.set(headerName, headerValue)
    }
  })
}

function updateCspVariables (csp: ContentSecurityPolicyValue, nonce?: string, scriptHashes?: Set<string>, styleHashes?: Set<string>) {
  if (csp === false) {
    return false
  }
  const generatedCsp = <ContentSecurityPolicyValue>Object.fromEntries(Object.entries(csp).map(([directive, value]) => {
    // Return boolean values unchanged
    if (typeof value === 'boolean') {
      return [directive, value]
    }
    // Make sure nonce placeholders are eliminated
    const sources = (typeof value === 'string') ? value.split(' ').map(token => token.trim()).filter(token => token) : value
    const modifiedSources = sources
      .map((source) => {
        if (source.startsWith('\'nonce-') || source === '\'nonce-{{nonce}}\'') {
          return nonce ? `'nonce-${nonce}'` : ''
        } else {
          return source
        }
      })
      .filter(source => source)

    if (['script-src', 'script-src-elem'].includes(directive) && scriptHashes) {
      modifiedSources.push(...scriptHashes)
    }
    if (['style-src', 'style-src-elem'].includes(directive) && styleHashes) {
      modifiedSources.push(...styleHashes)
    }

    return [directive, modifiedSources]
  }))
  return generatedCsp
}
