#!/usr/bin/env node -r esm
import Package from './package'

async function main() {
  // Read package at current directory
  const rootPackage = new Package()
  const workspacePackages = rootPackage.getWorkspacePackages()

  for (const pkg of workspacePackages) {
    if (pkg.options.autoFix) {
      pkg.autoFix()
    }
    if (pkg.options.build) {
      await pkg.build()
    }
  }
}

main().catch(console.error) // eslint-disable-line no-console
