#!/usr/bin/env node -r esm

import consola from 'consola'

import Package from './package'

async function main() {
  // Read package at current directory
  const rootPackage = new Package()
  const workspacePackages = rootPackage.getWorkspacePackages()

  for (const pkg of workspacePackages) {
    if (pkg.options.autoFix) {
      pkg.autoFix()
    }
    if (pkg.options.build) {
      if (process.argv.includes('--watch')) {
        pkg.watch()
      } else {
        await pkg.build()
      }
    }
  }
}

main().catch((error) => {
  consola.error(error + '')
  process.exit(1)
})
