#!/usr/bin/env node -r esm

import consola from 'consola'

import Package from './package.js'

async function main() {
  // Read package at current directory
  const rootPackage = new Package()
  const workspacePackages = rootPackage.getWorkspacePackages()

  const watch = process.argv.includes('--watch')

  if (watch) {
    consola.info('Watch mode')
  }

  // Step 1: Suffix an Build packages
  for (const pkg of workspacePackages) {
    if (pkg.options.suffix && pkg.options.suffix.length) {
      pkg.suffixAndVersion()
      pkg.writePackage()
    }

    if (pkg.options.build) {
      if (watch) {
        pkg.watch()
      } else {
        await pkg.build()
      }
    }
  }

  // Step 2: Link dependencies and fix packages
  for (const pkg of workspacePackages) {
    pkg.syncLinkedDependencies()
    pkg.autoFix()
    pkg.writePackage()
  }
}

main().catch((error) => {
  consola.error(error + '')
  process.exit(1)
})
