#!/bin/bash
set -e

if [ ! "$1" ]; then
  echo "Usage $0 [version]"
  exit 1
fi

yarn build

for dir in packages/* distributions/* ; do
  # echo "$dir"
  pushd $dir > /dev/null
  # if package is nuxt then publish with tag 2x
  if [ "$dir" = "distributions/nuxt" ]; then
    npm publish --tag 2x -q
  else
    npm publish -q
  fi
  popd > /dev/null
done

git tag -a v$1 -m v$1
git push --tags
