// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference types="nuxt3" />
/// <reference path=".nuxt/components.d.ts" />
/// <reference path=".nuxt/global-imports.d.ts" />
export {}
