// Declarations auto generated by `nuxt prepare`. Please do not manually modify this file.

/// <reference types="@nuxt/kit" />
/// <reference types="@nuxt/nitro" />
/// <reference types="@nuxt/pages" />
/// <reference types="@nuxt/meta" />
/// <reference types="@nuxt/component-discovery" />
