export const builder = 'webpack'
export { default as webpack } from 'webpack'
export { default as MiniCssExtractPlugin } from 'mini-css-extract-plugin'
export { default as WebpackBarPlugin } from 'webpackbar'
export { default as TsCheckerPlugin } from 'fork-ts-checker-webpack-plugin'
