tasks:
  install-and-dev:
    name: Install dependencies and start dev
    command: |
      pnpm install
      pnpm dev:prepare
      pnpm play
    triggeredBy:
      - postDevcontainerStart
      - manual
