name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
      - "*.md"

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Nuxt
        run: pnpm build

      - name: Lint (docs)
        run: pnpm lint:docs:fix

      - name: Typecheck (docs)
        run: pnpm typecheck:docs

      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8 # 7a166d7532b277f34e16238930461bf77f9d7ed8
