name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
      - "*.md"

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Nuxt
        run: pnpm build

      - name: Lint (docs)
        run: pnpm lint:docs:fix

      - name: Typecheck (docs)
        run: pnpm typecheck:docs

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
