name: changelog

on:
  push:
    branches:
      - main
      - 4.x
      - 3.x

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  update:
    if: github.repository_owner == 'nuxt' && !contains(github.event.head_commit.message, 'v3.') && !contains(github.event.head_commit.message, 'v4.') && !contains(github.event.head_commit.message, 'v5.')
    runs-on: ubuntu-24.04-arm

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: current
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - run: node ./scripts/update-changelog.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
