name: 'Dependency review'

on:
  pull_request:
    branches:
      - main
      - 4.x
      - 3.x
      - '!v[0-9]*'

permissions:
  contents: read

jobs:
  dependency-review:
    uses: nuxt/.github/.github/workflows/dependency-review.yml@main
    with:
      fail-on-provenance-change: true
