name: docs

on:
  pull_request:
    paths:
      - 'docs/**'
      - '*.md'
    branches:
      - main
      - 4.x
      - 3.x

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  link-checker:
    runs-on: ubuntu-24.04-arm
    steps:
      # Cache lychee results (e.g. to avoid hitting rate limits)
      - name: Restore lychee cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      # check links with Lychee
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Lychee link checker
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          # arguments with file types to check
          args: >-
            '-c=lychee.toml'
            './docs/**/*.md'
            './docs/**/*.html'
            './packages/*/src/**/*.ts'
            './packages/*/src/**/*.js'
            './packages/*/src/**/*.md'
          # fail the action on broken links
          fail: true
        env:
          # to be used in case rate limits are surpassed
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
