name: docs

on:
  merge_group:
  # autofix workflow will be triggered instead for PRs
  push:
    branches:
      - main
      - 4.x
      - 3.x
      - '!v[0-9]*'
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - '*.md'

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/tutorials/authenticate-with-github_token
permissions: {}

jobs:
  lint-docs:
    # autofix workflow handles PRs; run in merge queue and on push to maintenance branches
    if: github.event_name == 'merge_group' || (github.event_name == 'push' && github.ref_name != 'main')
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build (stub)
        run: pnpm dev:prepare

      - name: Lint (docs)
        run: pnpm lint:docs

      - name: Build Nuxt
        run: pnpm build

      - name: Typecheck (docs)
        run: pnpm typecheck:docs
