name: docs

on:
  push:
    paths:
      - "docs/**"
    branches:
      - main
      - 4.x
      - 3.x

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/tutorials/authenticate-with-github_token
permissions: {}

jobs:
  deploy-docs:
    runs-on: ubuntu-slim

    steps:
      - name: trigger docs deployment
        if: ${{ github.repository_owner == 'nuxt' && github.event_name == 'push' }}
        run: curl -fsS --max-time 30 --retry 3 --retry-delay 5 --retry-connrefused "${{ secrets.DOCS_WEBHOOK }}"
