name: chore

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  add-issue-labels:
    name: Add labels
    runs-on: ubuntu-latest
    if: github.repository == 'nuxt/nuxt'
    steps:
      - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
            // add 'pending triage' label if issue is created with no labels
            if (context.payload.issue.labels.length === 0) {
              github.rest.issues.addLabels({
                issue_number: context.payload.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['pending triage']
              })
            }
