name: CI

on:
  push:
    paths:
      - "**/package.json"
    branches:
      - main
      - 3.x
  pull_request:
    paths:
      - "**/package.json"
    branches:
      - main
      - 3.x
      - "!v[0-9]*"

permissions:
  contents: read

jobs:
  lint-monorepo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: corepack enable
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
      - name: Lint monorepo
        run: pnpm sherif -r multiple-dependency-versions
