name: ci

on:
  merge_group:
  push:
    paths:
      - '**/package.json'
      - 'pnpm-lock.yaml'
    branches:
      - main
      - 4.x
      - 3.x
  pull_request:
    paths:
      - '**/package.json'
      - 'pnpm-lock.yaml'
    branches:
      - main
      - 4.x
      - 3.x
      - '!v[0-9]*'

permissions:
  contents: read

jobs:
  lint-monorepo:
    # skip on push to main (already tested in merge queue) but run on push to maintenance branches
    if: github.event_name != 'push' || github.ref_name != 'main'
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1.15.0
        with:
          node-version: lts
          cache: true

      - parallel:
          - name: Lint monorepo
            run: vp exec sherif -r multiple-dependency-versions

          - name: Check engine ranges, peer dependency ranges and installed versions
            run: vp run test:engines
