name: CI

on:
  merge_group:
  push:
    paths:
      - '.github/workflows/**'
    branches:
      - main
      - 4.x
      - 3.x
  pull_request:
    paths:
      - '.github/workflows/**'
    branches:
      - main
      - 4.x
      - 3.x
      - '!v[0-9]*'

permissions:
  contents: read

jobs:
  lint-workflows:
    # skip on push to main (already tested in merge queue) but run on push to maintenance branches
    if: github.event_name != 'push' || github.ref_name != 'main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # From https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.7.12@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667
        with:
          args: -color
