name: ci

on:
  merge_group:
  push:
    paths:
      - '**/package.json'
      - 'pnpm-lock.yaml'
    branches:
      - main
      - 4.x
      - 3.x
  pull_request:
    paths:
      - '**/package.json'
      - 'pnpm-lock.yaml'
    branches:
      - main
      - 4.x
      - 3.x
      - '!v[0-9]*'

permissions:
  contents: read

jobs:
  lint-monorepo:
    # skip on push to main (already tested in merge queue) but run on push to maintenance branches
    if: github.event_name != 'push' || github.ref_name != 'main'
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint monorepo
        run: pnpm sherif -r multiple-dependency-versions

      - name: Check engine ranges, peer dependency ranges and installed versions
        run: pnpm test:engines
