name: CI

on:
  push:
    paths:
      - "**/package.json"
    branches:
      - main
      - 3.x
  pull_request:
    paths:
      - "**/package.json"
    branches:
      - main
      - 3.x
      - "!v[0-9]*"

permissions:
  contents: read

jobs:
  lint-monorepo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Lint monorepo
        run: pnpm sherif -r multiple-dependency-versions
