name: release

on:
  push:
    tags:
      - "v*"

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/tutorials/authenticate-with-github_token
permissions: {}

jobs:
  release:
    concurrency:
      group: release
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: current
          registry-url: "https://registry.npmjs.org/"
          package-manager-cache: false

      - name: 📦 Install dependencies
        run: pnpm install

      - name: Build (stub)
        run: pnpm dev:prepare

      - name: 🛠 Build and release project
        run: node scripts/release.ts
        env:
          TAG: ${{ startsWith(github.ref_name, 'v3.') && '3x' || startsWith(github.ref_name, 'v4.') && 'latest,4x' || startsWith(github.ref_name, 'v5.') && '5x' || 'latest' }}
