name: release

on:
  push:
    tags:
      - "v*"

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/tutorials/authenticate-with-github_token
permissions: {}

jobs:
  release:
    concurrency:
      group: release
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1.15.0
        with:
          node-version: latest
          registry-url: "https://registry.npmjs.org/"
          cache: false

      - name: Prepare
        run: vp run dev:prepare

      - name: 🛠 Build and release project
        run: node scripts/release.ts
        env:
          TAG: ${{ startsWith(github.ref_name, 'v3.') && '3x' || startsWith(github.ref_name, 'v4.') && 'latest,4x' || startsWith(github.ref_name, 'v5.') && '5x' || 'latest' }}
