name: chore
on:
  issues:
    types:
      opened

permissions:
  issues: write

jobs:
  stackblitz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: huang-julien/reproduire-sur-stackblitz@edd77eee0ffdae795c9dfd4e5b3b745740672439 # v1.0.3
        with:
          reproduction-heading: '### Reproduction'
